description: "Банковские карты"
get:
    securedBy: [TPSAuth]
    description: "Возвращает список карт"
    is: !include /is/simple/get-list.raml
    responses:
        200:
            body:
                application/json:
                    #type: !include schema/list.json
                    example: !include example/list.json
/{id}:
    uriParameters:
        id:
            description: "ID карты"
            type: integer
    get:
        securedBy: [TPSAuth]
        description: "Возвращает карту"
        is: !include /is/simple/get-details.raml
        responses:
            200:
                body:
                    application/json:
                        #type: !include schema/details.json
                        example: !include example/details.json
    delete:
        securedBy: [TPSAuth]
        description: "Отвязать карту"
        is: !include /is/delete.raml
/approve:
    put:
        securedBy: [TPSAuth]
        description: "Допривязать карту"
        is: !include /is/put.raml
        body:
            application/json:
                #type: !include schema/edit.json
                example: !include example/approve.json
/attach:
    get:
        securedBy: [TPSAuth]
        description: "Привязать карту"
        is: [code200, code304, code404, code401, code403, code429, code500]
        responses:
           200:
                body:
                    text/html:
                        #type: !include schema/edit.json
                        example: !include example/attach.html
        queryParameters:
            link:
                type: integer
                description: Привязка
                required: true
                minimum: 1
                example: 1